[package]
name = "gameboy-advanced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]

[dependencies]
core = { path = "core/"}

egui = "0.31.1"
eframe = "0.31.1"